http:
  port: 8000
  readTimeout: 20s
  writeTimeout: 20s
  maxHeaderBytes: 1

emailsService:
  url: "https://mailer.gasstrem.com/api/v1/email/company-registration"

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h #30 days

